### ISSUE TITLE
Add to logseq marketplace

### ISSUE THREAD

**Issue by daviddavo** [sethyuan/logseq-long-form#2]
This plugin is incredible. To make it easier to install for everyone, could you please add it to the marketplace?

https://github.com/logseq/marketplace

**Comment by sethyuan** [comment]
Hi @daviddavo , great suggestion! The plugin is on the marketplace now, you can find it by searching "long form".

**Comment by daviddavo** [comment]
Thank you! The plugin was featured on [Logseq Times](https://www.logseqtimes.com/) and now more people can test it easier.
