### ISSUE TITLE
license code update

### ISSUE THREAD

**Issue by Mauricinho** [sethyuan/logseq-long-form#3]
Hi Seth Yuan,
I had to reinstall my logseq and. now my license code for longform is no longer valid. Cna you send me a new one?
Best regards, Maurits

**Comment by sethyuan** [comment]
Sure, I sent the email to you, please be sure to check it out.

**Comment by Mauricinho** [comment]
Sorry, but I did not see the email. Could you resend it?

**Comment by sethyuan** [comment]
Can you pm me Discord and give me the email you used when you made the purchase? My Discord handle is `@sethyuan`.

**Comment by Mauricinho** [comment]
Treid to add you on discord so that I can PM. Not so good at home at discord :-)

**Comment by Mauricinho** [comment]
I see now that you email got in my spambox. So that was the problem
probably.

Contacted you on discord, but not there all the ime to be honest ;-)

**Comment by sethyuan** [comment]
Sent.
