### ISSUE TITLE
Please give me access to a new license code

### ISSUE THREAD

**Issue by mailomimo** [sethyuan/logseq-long-form#5]
Hello, My email is biancapatricia28@yahoo.com. I bought this plugin on Apr30 and I had this license plate:  ZVumN0GyZittcmJJOYAiuBq1yhnAiZvmMKmwl/gxdDi6gJ6up59ACJOgGRXqhB77 . However, my Logseq crashed today and deleted all my files. It tells me that the token has expired, can you please give me access to a new license code? I am a poor college student and would be very appreciative if I won't have to pay twice for the same feature because of an app bug. Thank you.

**Comment by sethyuan** [comment]
An email with a new code is sent to you, please check it out.

**Comment by mailomimo** [comment]
Thank you!!!!
